INSERT INTO CUSTOMER(ADDRESS,CITY,EDAD,FIRST_NAME,LAST_NAME) VALUES ('Calle 1','Barranquilla','22','Geovanny','Mendoza');
INSERT INTO CUSTOMER(ADDRESS,CITY,EDAD,FIRST_NAME,LAST_NAME) VALUES ('Calle 2','Valledupar','18','Valeria','Ahumada');
INSERT INTO CUSTOMER(ADDRESS,CITY,EDAD,FIRST_NAME,LAST_NAME) VALUES ('Calle 3','Santa Marta','30','Matias','Mendoza');

